// ==================== 200 NOVOS COMPOSTOS + RECEITAS COMPLETAS ====================
// Cada receita combina EXATAMENTE 2 itens
// Todos os nomes e símbolos são scientificamente corretos
// Sem duplicatas ou variações desnecessárias

const NEW_COMPOUNDS = [
    // GRUPO 1: ÓXIDOS BÁSICOS
    { id: 'sodium_oxide', name: 'Óxido de Sódio', symbol: 'Na₂O', category: 'INORGANIC_COMPOUND', desc: 'Óxido branco, reage vigorosamente com água.' },
    { id: 'potassium_oxide', name: 'Óxido de Potássio', symbol: 'K₂O', category: 'INORGANIC_COMPOUND', desc: 'Óxido básico, extremamente higroscópico.' },
    { id: 'calcium_oxide', name: 'Óxido de Cálcio', symbol: 'CaO', category: 'INORGANIC_COMPOUND', desc: 'Cal viva, óxido branco altamente reativo.' },
    { id: 'magnesium_oxide', name: 'Óxido de Magnésio', symbol: 'MgO', category: 'INORGANIC_COMPOUND', desc: 'Magnésia, pó branco refratário.' },
    { id: 'aluminum_oxide', name: 'Óxido de Alumínio', symbol: 'Al₂O₃', category: 'INORGANIC_COMPOUND', desc: 'Alumina, abrasivo duro branco.' },
    { id: 'iron_oxide_red', name: 'Óxido de Ferro III', symbol: 'Fe₂O₃', category: 'INORGANIC_COMPOUND', desc: 'Ferrugem vermelha, pigmento natural.' },
    { id: 'copper_oxide_black', name: 'Óxido de Cobre II', symbol: 'CuO', category: 'INORGANIC_COMPOUND', desc: 'Óxido preto do cobre.' },
    { id: 'zinc_oxide', name: 'Óxido de Zinco', symbol: 'ZnO', category: 'INORGANIC_COMPOUND', desc: 'Branco de zinco, pigmento opaco.' },
    { id: 'phosphorus_pentoxide', name: 'Pentóxido de Fósforo', symbol: 'P₂O₅', category: 'INORGANIC_COMPOUND', desc: 'Desumidificante extremamente potente.' },
    { id: 'nitrogen_monoxide', name: 'Monóxido de Nitrogênio', symbol: 'NO', category: 'INORGANIC_COMPOUND', desc: 'Gás incolor, precursor de outros óxidos.' },
    
    // GRUPO 2: BASES E HIDRÓXIDOS
    { id: 'sodium_hydroxide', name: 'Hidróxido de Sódio', symbol: 'NaOH', category: 'INORGANIC_COMPOUND', desc: 'Soda cáustica, base forte corrosiva.' },
    { id: 'potassium_hydroxide', name: 'Hidróxido de Potássio', symbol: 'KOH', category: 'INORGANIC_COMPOUND', desc: 'Potassa cáustica, base forte deliquescente.' },
    { id: 'calcium_hydroxide', name: 'Hidróxido de Cálcio', symbol: 'Ca(OH)₂', category: 'INORGANIC_COMPOUND', desc: 'Cal hidratada, base fraca levemente solúvel.' },
    { id: 'magnesium_hydroxide', name: 'Hidróxido de Magnésio', symbol: 'Mg(OH)₂', category: 'INORGANIC_COMPOUND', desc: 'Leite de magnésia, laxante suave.' },
    { id: 'aluminum_hydroxide', name: 'Hidróxido de Alumínio', symbol: 'Al(OH)₃', category: 'INORGANIC_COMPOUND', desc: 'Gelatinoso branco, retardante de chama.' },
    { id: 'ammonia_aqueous', name: 'Solução de Amônia', symbol: 'NH₃(aq)', category: 'INORGANIC_COMPOUND', desc: 'Amônia dissolvida em água, base fraca.' },
    { id: 'copper_hydroxide', name: 'Hidróxido de Cobre II', symbol: 'Cu(OH)₂', category: 'INORGANIC_COMPOUND', desc: 'Azul turquesa, fungicida natural.' },
    { id: 'iron_hydroxide_ferric', name: 'Hidróxido de Ferro III', symbol: 'Fe(OH)₃', category: 'INORGANIC_COMPOUND', desc: 'Gelatinoso marrom-avermelhado.' },
    { id: 'zinc_hydroxide', name: 'Hidróxido de Zinco', symbol: 'Zn(OH)₂', category: 'INORGANIC_COMPOUND', desc: 'Branco gelatinoso, anfótero.' },
    { id: 'barium_hydroxide', name: 'Hidróxido de Bário', symbol: 'Ba(OH)₂', category: 'INORGANIC_COMPOUND', desc: 'Base forte solúvel, cristais incolores.' },
    
    // GRUPO 3: NITRATOS
    { id: 'potassium_nitrate', name: 'Nitrato de Potássio', symbol: 'KNO₃', category: 'INORGANIC_COMPOUND', desc: 'Salitre, fertilizante e ingrediente de pólvora.' },
    { id: 'sodium_nitrate', name: 'Nitrato de Sódio', symbol: 'NaNO₃', category: 'INORGANIC_COMPOUND', desc: 'Salitre do Chile, conservante alimentar.' },
    { id: 'calcium_nitrate', name: 'Nitrato de Cálcio', symbol: 'Ca(NO₃)₂', category: 'INORGANIC_COMPOUND', desc: 'Sal deliquescente, fertilizante solúvel.' },
    { id: 'ammonium_nitrate', name: 'Nitrato de Amônio', symbol: 'NH₄NO₃', category: 'INORGANIC_COMPOUND', desc: 'Fertilizante de alto rendimento.' },
    { id: 'magnesium_nitrate', name: 'Nitrato de Magnésio', symbol: 'Mg(NO₃)₂', category: 'INORGANIC_COMPOUND', desc: 'Sal deliquescente incolor.' },
    { id: 'aluminum_nitrate', name: 'Nitrato de Alumínio', symbol: 'Al(NO₃)₃', category: 'INORGANIC_COMPOUND', desc: 'Sal deliquescente, coagulante.' },
    { id: 'copper_nitrate', name: 'Nitrato de Cobre II', symbol: 'Cu(NO₃)₂', category: 'INORGANIC_COMPOUND', desc: 'Azul celeste, oxidante forte.' },
    { id: 'silver_nitrate', name: 'Nitrato de Prata', symbol: 'AgNO₃', category: 'INORGANIC_COMPOUND', desc: 'Cristais incolores, fotossensível.' },
    { id: 'lead_nitrate', name: 'Nitrato de Chumbo', symbol: 'Pb(NO₃)₂', category: 'INORGANIC_COMPOUND', desc: 'Cristais incolores, tóxico.' },
    { id: 'zinc_nitrate', name: 'Nitrato de Zinco', symbol: 'Zn(NO₃)₂', category: 'INORGANIC_COMPOUND', desc: 'Incolor deliquescente.' },
    
    // GRUPO 4: SULFATOS
    { id: 'potassium_sulfate', name: 'Sulfato de Potássio', symbol: 'K₂SO₄', category: 'INORGANIC_COMPOUND', desc: 'Sal branco, fertilizante sem cloro.' },
    { id: 'sodium_sulfate', name: 'Sulfato de Sódio', symbol: 'Na₂SO₄', category: 'INORGANIC_COMPOUND', desc: 'Sal de Glauber, usado em detergentes.' },
    { id: 'calcium_sulfate', name: 'Sulfato de Cálcio', symbol: 'CaSO₄', category: 'INORGANIC_COMPOUND', desc: 'Gesso, mineral branco.' },
    { id: 'magnesium_sulfate', name: 'Sulfato de Magnésio', symbol: 'MgSO₄', category: 'INORGANIC_COMPOUND', desc: 'Sal de Epsom, usado em medicina.' },
    { id: 'aluminum_sulfate', name: 'Sulfato de Alumínio', symbol: 'Al₂(SO₄)₃', category: 'INORGANIC_COMPOUND', desc: 'Alumem, coagulante em tratamento de água.' },
    { id: 'copper_sulfate', name: 'Sulfato de Cobre II', symbol: 'CuSO₄', category: 'INORGANIC_COMPOUND', desc: 'Azul intenso, fungicida agrícola.' },
    { id: 'iron_sulfate', name: 'Sulfato de Ferro II', symbol: 'FeSO₄', category: 'INORGANIC_COMPOUND', desc: 'Vitriol verde, tonificante mineral.' },
    { id: 'iron_sulfate_ferric', name: 'Sulfato de Ferro III', symbol: 'Fe₂(SO₄)₃', category: 'INORGANIC_COMPOUND', desc: 'Sal amarelado, coagulante.' },
    { id: 'zinc_sulfate', name: 'Sulfato de Zinco', symbol: 'ZnSO₄', category: 'INORGANIC_COMPOUND', desc: 'Sal branco incolor, adstringente.' },
    { id: 'barium_sulfate', name: 'Sulfato de Bário', symbol: 'BaSO₄', category: 'INORGANIC_COMPOUND', desc: 'Branco puro insolúvel, contraste radiológico.' },
    
    // GRUPO 5: CARBONATOS
    { id: 'sodium_carbonate', name: 'Carbonato de Sódio', symbol: 'Na₂CO₃', category: 'INORGANIC_COMPOUND', desc: 'Barrilha, usado em vidro e detergentes.' },
    { id: 'potassium_carbonate', name: 'Carbonato de Potássio', symbol: 'K₂CO₃', category: 'INORGANIC_COMPOUND', desc: 'Potassa, usado em vidro e sabão.' },
    { id: 'magnesium_carbonate', name: 'Carbonato de Magnésio', symbol: 'MgCO₃', category: 'INORGANIC_COMPOUND', desc: 'Pó branco, usado em farmácia.' },
    { id: 'barium_carbonate', name: 'Carbonato de Bário', symbol: 'BaCO₃', category: 'INORGANIC_COMPOUND', desc: 'Branco opaco, usado em cerâmicas.' },
    { id: 'copper_carbonate', name: 'Carbonato de Cobre II', symbol: 'CuCO₃', category: 'INORGANIC_COMPOUND', desc: 'Verde azulado, mineral natural.' },
    { id: 'lead_carbonate', name: 'Carbonato de Chumbo', symbol: 'PbCO₃', category: 'INORGANIC_COMPOUND', desc: 'Branco cristalino, tóxico.' },
    { id: 'zinc_carbonate', name: 'Carbonato de Zinco', symbol: 'ZnCO₃', category: 'INORGANIC_COMPOUND', desc: 'Branco cristalino.' },
    { id: 'ammonium_carbonate', name: 'Carbonato de Amônio', symbol: '(NH₄)₂CO₃', category: 'INORGANIC_COMPOUND', desc: 'Sal aromático de amônia.' },
    { id: 'sodium_bicarbonate', name: 'Bicarbonato de Sódio', symbol: 'NaHCO₃', category: 'INORGANIC_COMPOUND', desc: 'Pó de fermento, desodorizante.' },
    { id: 'potassium_bicarbonate', name: 'Bicarbonato de Potássio', symbol: 'KHCO₃', category: 'INORGANIC_COMPOUND', desc: 'Sal solúvel, similar ao bicarbonato de sódio.' },
    
    // GRUPO 6: CLORETOS
    { id: 'potassium_chloride', name: 'Cloreto de Potássio', symbol: 'KCl', category: 'INORGANIC_COMPOUND', desc: 'Sal solúvel, fertilizante e substituto de sal.' },
    { id: 'calcium_chloride', name: 'Cloreto de Cálcio', symbol: 'CaCl₂', category: 'INORGANIC_COMPOUND', desc: 'Sal higroscópico, desumidificador.' },
    { id: 'magnesium_chloride', name: 'Cloreto de Magnésio', symbol: 'MgCl₂', category: 'INORGANIC_COMPOUND', desc: 'Sal deliquescente incolor.' },
    { id: 'aluminum_chloride', name: 'Cloreto de Alumínio', symbol: 'AlCl₃', category: 'INORGANIC_COMPOUND', desc: 'Catalisador químico importante.' },
    { id: 'copper_chloride', name: 'Cloreto de Cobre II', symbol: 'CuCl₂', category: 'INORGANIC_COMPOUND', desc: 'Amarelado, oxidante importante.' },
    { id: 'zinc_chloride', name: 'Cloreto de Zinco', symbol: 'ZnCl₂', category: 'INORGANIC_COMPOUND', desc: 'Cristais incolores, higroscópico.' },
    { id: 'iron_chloride_ferric', name: 'Cloreto de Ferro III', symbol: 'FeCl₃', category: 'INORGANIC_COMPOUND', desc: 'Amarelo-marrom, oxidante forte.' },
    { id: 'ammonium_chloride', name: 'Cloreto de Amônio', symbol: 'NH₄Cl', category: 'INORGANIC_COMPOUND', desc: 'Sal volátil, usado em baterias.' },
    { id: 'silver_chloride', name: 'Cloreto de Prata', symbol: 'AgCl', category: 'INORGANIC_COMPOUND', desc: 'Branco fotossensível, fotografia.' },
    { id: 'lead_chloride', name: 'Cloreto de Chumbo II', symbol: 'PbCl₂', category: 'INORGANIC_COMPOUND', desc: 'Branco cristalino.' },
    
    // GRUPO 7: FOSFATOS
    { id: 'sodium_phosphate_tribasic', name: 'Fosfato de Sódio Tribásico', symbol: 'Na₃PO₄', category: 'INORGANIC_COMPOUND', desc: 'Sal branco, usado em detergentes.' },
    { id: 'potassium_phosphate_tribasic', name: 'Fosfato de Potássio Tribásico', symbol: 'K₃PO₄', category: 'INORGANIC_COMPOUND', desc: 'Sal branco deliquescente.' },
    { id: 'calcium_phosphate', name: 'Fosfato de Cálcio', symbol: 'Ca₃(PO₄)₂', category: 'INORGANIC_COMPOUND', desc: 'Mineral principal dos ossos e dentes.' },
    { id: 'ammonium_phosphate_dibasic', name: 'Fosfato de Amônio Dibásico', symbol: '(NH₄)₂HPO₄', category: 'INORGANIC_COMPOUND', desc: 'Fertilizante de alta concentração.' },
    { id: 'aluminum_phosphate', name: 'Fosfato de Alumínio', symbol: 'AlPO₄', category: 'INORGANIC_COMPOUND', desc: 'Branco cristalino.' },
    { id: 'iron_phosphate', name: 'Fosfato de Ferro III', symbol: 'FePO₄', category: 'INORGANIC_COMPOUND', desc: 'Amarelado cristalino.' },
    { id: 'copper_phosphate', name: 'Fosfato de Cobre II', symbol: 'Cu₃(PO₄)₂', category: 'INORGANIC_COMPOUND', desc: 'Verde azulado.' },
    { id: 'zinc_phosphate', name: 'Fosfato de Zinco', symbol: 'Zn₃(PO₄)₂', category: 'INORGANIC_COMPOUND', desc: 'Branco, protetor anti-corrosão.' },
    { id: 'magnesium_phosphate', name: 'Fosfato de Magnésio', symbol: 'Mg₃(PO₄)₂', category: 'INORGANIC_COMPOUND', desc: 'Branco cristalino.' },
    { id: 'lead_phosphate', name: 'Fosfato de Chumbo', symbol: 'Pb₃(PO₄)₂', category: 'INORGANIC_COMPOUND', desc: 'Branco opaco.' },
    
    // GRUPO 8: ÁCIDOS
    { id: 'hydrofluoric_acid', name: 'Ácido Fluorídrico', symbol: 'HF', category: 'INORGANIC_COMPOUND', desc: 'Ácido fraco, gravador de vidro.' },
    { id: 'hydrochloric_acid_conc', name: 'Ácido Clorídrico Concentrado', symbol: 'HCl(conc)', category: 'INORGANIC_COMPOUND', desc: 'Ácido mineral muito corrosivo.' },
    { id: 'phosphoric_acid', name: 'Ácido Fosfórico', symbol: 'H₃PO₄', category: 'INORGANIC_COMPOUND', desc: 'Ácido fraco, usado em fertilizantes.' },
    { id: 'sulfurous_acid', name: 'Ácido Sulfuroso', symbol: 'H₂SO₃', category: 'INORGANIC_COMPOUND', desc: 'Ácido fraco, conservante alimentar.' },
    { id: 'boric_acid', name: 'Ácido Bórico', symbol: 'H₃BO₃', category: 'INORGANIC_COMPOUND', desc: 'Ácido fraco, antisséptico leve.' },
    { id: 'silicic_acid', name: 'Ácido Silícico', symbol: 'H₂SiO₃', category: 'INORGANIC_COMPOUND', desc: 'Ácido muito fraco, precursor de sílica gel.' },
    { id: 'nitrous_acid', name: 'Ácido Nitroso', symbol: 'HNO₂', category: 'INORGANIC_COMPOUND', desc: 'Ácido fraco instável.' },
    { id: 'peroxide_hydrogen_conc', name: 'Peróxido de Hidrogênio Concentrado', symbol: 'H₂O₂(conc)', category: 'INORGANIC_COMPOUND', desc: 'Oxidante forte e instável.' },
    { id: 'chromic_acid', name: 'Ácido Crômico', symbol: 'H₂CrO₄', category: 'INORGANIC_COMPOUND', desc: 'Oxidante muito forte e tóxico.' },
    { id: 'hypochlorous_acid', name: 'Ácido Hipocloro', symbol: 'HClO', category: 'INORGANIC_COMPOUND', desc: 'Ácido fraco, desinfetante.' },
    
    // GRUPO 9: COMPOSTOS ESPECIAIS
    { id: 'hydrogen_sulfide', name: 'Sulfeto de Hidrogênio', symbol: 'H₂S', category: 'INORGANIC_COMPOUND', desc: 'Gás de odor desagradável, redutor.' },
    { id: 'ammonia_gas', name: 'Amônia Gasosa', symbol: 'NH₃', category: 'INORGANIC_COMPOUND', desc: 'Gás incolor pungente, base fraca.' },
    { id: 'carbon_disulfide', name: 'Dissulfeto de Carbono', symbol: 'CS₂', category: 'INORGANIC_COMPOUND', desc: 'Líquido incolor, solvente.' },
    { id: 'chlorine_gas', name: 'Cloro Gasoso', symbol: 'Cl₂', category: 'INORGANIC_COMPOUND', desc: 'Gás verde-amarelado, oxidante forte.' },
    { id: 'bromine_liquid', name: 'Bromo Líquido', symbol: 'Br₂', category: 'INORGANIC_COMPOUND', desc: 'Líquido marrom-avermelhado, tóxico.' },
    { id: 'iodine_solid', name: 'Iodo Sólido', symbol: 'I₂', category: 'INORGANIC_COMPOUND', desc: 'Cristais pretos brilhantes.' },
    { id: 'sodium_peroxide', name: 'Peróxido de Sódio', symbol: 'Na₂O₂', category: 'INORGANIC_COMPOUND', desc: 'Pó amarelo, libera oxigênio.' },
    { id: 'barium_peroxide', name: 'Peróxido de Bário', symbol: 'BaO₂', category: 'INORGANIC_COMPOUND', desc: 'Pó cinza, oxidante forte.' },
    { id: 'calcium_peroxide', name: 'Peróxido de Cálcio', symbol: 'CaO₂', category: 'INORGANIC_COMPOUND', desc: 'Pó amarelado, blanqueador.' },
    { id: 'hydrogen_peroxide_solution', name: 'Peróxido de Hidrogênio Diluído', symbol: 'H₂O₂(diluted)', category: 'INORGANIC_COMPOUND', desc: 'Desinfetante comum, oxidante fraco.' },
    
    // GRUPO 10: HIDROCARBONETOS
    { id: 'ethane', name: 'Etano', symbol: 'C₂H₆', category: 'ORGANIC_COMPOUND', desc: 'Hidrocarboneto alifático saturado.' },
    { id: 'propane', name: 'Propano', symbol: 'C₃H₈', category: 'ORGANIC_COMPOUND', desc: 'Gás combustível de cozinha.' },
    { id: 'butane', name: 'Butano', symbol: 'C₄H₁₀', category: 'ORGANIC_COMPOUND', desc: 'Gás combustível de isqueiro.' },
    { id: 'pentane', name: 'Pentano', symbol: 'C₅H₁₂', category: 'ORGANIC_COMPOUND', desc: 'Hidrocarboneto alifático, solvente.' },
    { id: 'hexane', name: 'Hexano', symbol: 'C₆H₁₄', category: 'ORGANIC_COMPOUND', desc: 'Solvente não-polar usado em análises.' },
    { id: 'ethylene', name: 'Etileno', symbol: 'C₂H₄', category: 'ORGANIC_COMPOUND', desc: 'Alqueno, hormônio vegetal.' },
    { id: 'acetylene', name: 'Acetileno', symbol: 'C₂H₂', category: 'ORGANIC_COMPOUND', desc: 'Alquino, combustível de soldagem.' },
    { id: 'toluene', name: 'Tolueno', symbol: 'C₇H₈', category: 'ORGANIC_COMPOUND', desc: 'Metilbenzeno, solvente importante.' },
    { id: 'xylene', name: 'Xileno', symbol: 'C₈H₁₀', category: 'ORGANIC_COMPOUND', desc: 'Dimetilbenzeno isômero, solvente.' },
    { id: 'naphthalene', name: 'Naftaleno', symbol: 'C₁₀H₈', category: 'ORGANIC_COMPOUND', desc: 'Hidrocarboneto policíclico, antimofo.' },
    
    // GRUPO 11: ÁLCOOIS
    { id: 'methanol', name: 'Metanol', symbol: 'CH₃OH', category: 'ORGANIC_COMPOUND', desc: 'Álcool de madeira, combustível.' },
    { id: 'isopropanol', name: 'Isopropanol', symbol: 'C₃H₇OH', category: 'ORGANIC_COMPOUND', desc: 'Álcool isopropílico, desinfetante.' },
    { id: 'glycerol', name: 'Glicerol', symbol: 'C₃H₈O₃', category: 'ORGANIC_COMPOUND', desc: 'Triol viscoso, humectante.' },
    { id: 'phenol_pure', name: 'Fenol Puro', symbol: 'C₆H₅OH', category: 'ORGANIC_COMPOUND', desc: 'Ácido fraco aromático, desinfetante.' },
    { id: 'resorcinol', name: 'Resorcinol', symbol: 'C₆H₄(OH)₂', category: 'ORGANIC_COMPOUND', desc: 'Diidroxibenzeno, usado em resinas.' },
    { id: 'hydroquinone', name: 'Hidroquinona', symbol: 'C₆H₄(OH)₂', category: 'ORGANIC_COMPOUND', desc: 'Diidroxibenzeno, redutor fotográfico.' },
    { id: 'ethylene_glycol', name: 'Etilenoglicol', symbol: 'C₂H₆O₂', category: 'ORGANIC_COMPOUND', desc: 'Diol, anticongelante.' },
    { id: 'propylene_glycol', name: 'Propilenoglicol', symbol: 'C₃H₈O₂', category: 'ORGANIC_COMPOUND', desc: 'Diol, humectante de uso farmacêutico.' },
    { id: 'sorbitol', name: 'Sorbitol', symbol: 'C₆H₁₄O₆', category: 'ORGANIC_COMPOUND', desc: 'Polialcol usado como adoçante.' },
    { id: 'xylitol', name: 'Xilitol', symbol: 'C₅H₁₂O₅', category: 'ORGANIC_COMPOUND', desc: 'Adoçante natural encontrado em frutas.' },
    
    // GRUPO 12: ALDEÍDOS E CETONAS
    { id: 'formaldehyde', name: 'Formaldeído', symbol: 'CH₂O', category: 'ORGANIC_COMPOUND', desc: 'Aldeído simples, preservante.' },
    { id: 'acetaldehyde', name: 'Acetadeído', symbol: 'CH₃CHO', category: 'ORGANIC_COMPOUND', desc: 'Aldeído intermediário.' },
    { id: 'propanal', name: 'Propanal', symbol: 'C₂H₅CHO', category: 'ORGANIC_COMPOUND', desc: 'Aldeído de cadeia curta.' },
    { id: 'butanal', name: 'Butanal', symbol: 'C₃H₇CHO', category: 'ORGANIC_COMPOUND', desc: 'Aldeído com odor característico.' },
    { id: 'benzaldehyde', name: 'Benzaldeído', symbol: 'C₆H₅CHO', category: 'ORGANIC_COMPOUND', desc: 'Aldeído aromático, aroma de amêndoa.' },
    { id: 'butanone', name: 'Butanona', symbol: 'C₂H₅COCH₃', category: 'ORGANIC_COMPOUND', desc: 'Cetona de cadeia média.' },
    { id: 'cyclohexanone', name: 'Ciclohexanona', symbol: 'C₆H₁₀O', category: 'ORGANIC_COMPOUND', desc: 'Cetona cíclica.' },
    { id: 'vanillin', name: 'Vanilina', symbol: 'C₈H₈O₃', category: 'ORGANIC_COMPOUND', desc: 'Aldeído aromático, sabor de baunilha.' },
    { id: 'camphor', name: 'Cânfora', symbol: 'C₁₀H₁₆O', category: 'ORGANIC_COMPOUND', desc: 'Cetona bicíclica, odor pungente.' },
    { id: 'menthone', name: 'Mentona', symbol: 'C₁₀H₁₈O', category: 'ORGANIC_COMPOUND', desc: 'Cetona do óleo de menta.' },
    
    // GRUPO 13: ÁCIDOS CARBOXÍLICOS
    { id: 'formic_acid', name: 'Ácido Fórmico', symbol: 'HCOOH', category: 'ORGANIC_COMPOUND', desc: 'Ácido de formiga, ácido mais simples.' },
    { id: 'acetic_acid_pure', name: 'Ácido Acético Puro', symbol: 'CH₃COOH', category: 'ORGANIC_COMPOUND', desc: 'Vinagre concentrado, ácido fraco.' },
    { id: 'propionic_acid', name: 'Ácido Propiônico', symbol: 'C₂H₅COOH', category: 'ORGANIC_COMPOUND', desc: 'Ácido de cadeia curta, conservante.' },
    { id: 'butyric_acid', name: 'Ácido Butírico', symbol: 'C₃H₇COOH', category: 'ORGANIC_COMPOUND', desc: 'Odor de manteiga rançosa.' },
    { id: 'palmitic_acid', name: 'Ácido Palmítico', symbol: 'C₁₆H₃₂O₂', category: 'ORGANIC_COMPOUND', desc: 'Ácido graxo saturado.' },
    { id: 'stearic_acid', name: 'Ácido Esteárico', symbol: 'C₁₈H₃₆O₂', category: 'ORGANIC_COMPOUND', desc: 'Ácido graxo saturado, vela.' },
    { id: 'oleic_acid', name: 'Ácido Oléico', symbol: 'C₁₈H₃₄O₂', category: 'ORGANIC_COMPOUND', desc: 'Ácido graxo insaturado, fluido.' },
    { id: 'linoleic_acid', name: 'Ácido Linoleico', symbol: 'C₁₈H₃₂O₂', category: 'ORGANIC_COMPOUND', desc: 'Ácido graxo essencial ômega-6.' },
    { id: 'benzoic_acid', name: 'Ácido Benzóico', symbol: 'C₆H₅COOH', category: 'ORGANIC_COMPOUND', desc: 'Ácido aromático, conservante.' },
    { id: 'salicylic_acid', name: 'Ácido Salicílico', symbol: 'C₇H₆O₃', category: 'ORGANIC_COMPOUND', desc: 'Beta-hidroxi-ácido, esfoliante.' },
    
    // GRUPO 14: ÉSTERES
    { id: 'methyl_formate', name: 'Formiato de Metila', symbol: 'HCOOCH₃', category: 'ORGANIC_COMPOUND', desc: 'Éster simples.' },
    { id: 'ethyl_acetate', name: 'Acetato de Etila', symbol: 'CH₃COOC₂H₅', category: 'ORGANIC_COMPOUND', desc: 'Éster com odor agradável.' },
    { id: 'methyl_acetate', name: 'Acetato de Metila', symbol: 'CH₃COOCH₃', category: 'ORGANIC_COMPOUND', desc: 'Éster volátil.' },
    { id: 'isopropyl_acetate', name: 'Acetato de Isopropila', symbol: 'CH₃COOCH(CH₃)₂', category: 'ORGANIC_COMPOUND', desc: 'Éster aromático.' },
    { id: 'butyl_acetate', name: 'Acetato de Butila', symbol: 'CH₃COOC₄H₉', category: 'ORGANIC_COMPOUND', desc: 'Éster de odor frutado.' },
    { id: 'methyl_benzoate', name: 'Benzoato de Metila', symbol: 'C₆H₅COOCH₃', category: 'ORGANIC_COMPOUND', desc: 'Éster aromático, aroma morango.' },
    { id: 'methyl_salicylate', name: 'Salicilato de Metila', symbol: 'C₆H₄(OH)COOCH₃', category: 'ORGANIC_COMPOUND', desc: 'Óleo de inverno, analgésico tópico.' },
    { id: 'ethylene_diacetate', name: 'Diacetato de Etileno', symbol: '(CH₃CO)₂OC₂H₄', category: 'ORGANIC_COMPOUND', desc: 'Diéster.' },
    { id: 'tributyl_phosphate', name: 'Fosfato de Tributila', symbol: '(C₄H₉O)₃PO', category: 'ORGANIC_COMPOUND', desc: 'Plastificante industrial.' },
    { id: 'dibutyl_phthalate', name: 'Ftalato de Dibutila', symbol: 'C₆H₄(COOC₄H₉)₂', category: 'ORGANIC_COMPOUND', desc: 'Plastificante PVC.' },
    
    // GRUPO 15: AMINAS E AMIDAS
    { id: 'methylamine', name: 'Metilamina', symbol: 'CH₃NH₂', category: 'ORGANIC_COMPOUND', desc: 'Amina primária, odor de peixe.' },
    { id: 'dimethylamine', name: 'Dimetilamina', symbol: '(CH₃)₂NH', category: 'ORGANIC_COMPOUND', desc: 'Amina secundária.' },
    { id: 'trimethylamine', name: 'Trimetilamina', symbol: '(CH₃)₃N', category: 'ORGANIC_COMPOUND', desc: 'Amina terciária, odor pungente.' },
    { id: 'aniline', name: 'Anilina', symbol: 'C₆H₅NH₂', category: 'ORGANIC_COMPOUND', desc: 'Amina aromática, precursor de corantes.' },
    { id: 'formamide', name: 'Formamida', symbol: 'HCONH₂', category: 'ORGANIC_COMPOUND', desc: 'Amida simples, solvente.' },
    { id: 'acetamide', name: 'Acetamida', symbol: 'CH₃CONH₂', category: 'ORGANIC_COMPOUND', desc: 'Amida, umectante.' },
    { id: 'benzamide', name: 'Benzamida', symbol: 'C₆H₅CONH₂', category: 'ORGANIC_COMPOUND', desc: 'Amida aromática.' },
    { id: 'dimethylformamide', name: 'Dimetilformamida', symbol: 'HCON(CH₃)₂', category: 'ORGANIC_COMPOUND', desc: 'Amida, solvente polar.' },
    { id: 'dimethylacetamide', name: 'Dimetilacetamida', symbol: 'CH₃CON(CH₃)₂', category: 'ORGANIC_COMPOUND', desc: 'Amida, solvente.' },
    { id: 'urea_pure', name: 'Ureia Pura', symbol: 'CO(NH₂)₂', category: 'ORGANIC_COMPOUND', desc: 'Diamida, metabólito de proteína.' },
    
    // GRUPO 16: COMPOSTOS NITROGENADOS
    { id: 'nitrobenzene', name: 'Nitrobenzeno', symbol: 'C₆H₅NO₂', category: 'ORGANIC_COMPOUND', desc: 'Composto aromático nitrogenado, solvente.' },
    { id: 'nitromethane', name: 'Nitrometano', symbol: 'CH₃NO₂', category: 'ORGANIC_COMPOUND', desc: 'Nitro-alcano, combustível.' },
    { id: 'nitroethane', name: 'Nitroetano', symbol: 'C₂H₅NO₂', category: 'ORGANIC_COMPOUND', desc: 'Nitro-alcano.' },
    { id: 'trinitrotoluene', name: 'Trinitrotolueno', symbol: 'C₇H₅N₃O₆', category: 'ORGANIC_COMPOUND', desc: 'TNT, explosivo importante.' },
    { id: 'nitroglycerin', name: 'Nitroglicerina', symbol: 'C₃H₅N₃O₉', category: 'ORGANIC_COMPOUND', desc: 'Dinamita, explosivo potente.' },
    { id: 'cyanogen', name: 'Cianog ênio', symbol: '(CN)₂', category: 'ORGANIC_COMPOUND', desc: 'Gás tóxico incolor.' },
    { id: 'hydrogen_cyanide', name: 'Cianeto de Hidrogênio', symbol: 'HCN', category: 'ORGANIC_COMPOUND', desc: 'Gás altamente tóxico.' },
    { id: 'acetonitrile', name: 'Acetonitrila', symbol: 'CH₃CN', category: 'ORGANIC_COMPOUND', desc: 'Nitrila, solvente polar.' },
    { id: 'benzonitrile', name: 'Benzonitrila', symbol: 'C₆H₅CN', category: 'ORGANIC_COMPOUND', desc: 'Nitrila aromática.' },
    { id: 'thiocyanate', name: 'Tiocianato', symbol: 'SCN⁻', category: 'INORGANIC_COMPOUND', desc: 'Íon tiocianato.' },
    
    // GRUPO 17: AÇÚCARES
    { id: 'fructose', name: 'Frutose', symbol: 'C₆H₁₂O₆', category: 'ORGANIC_COMPOUND', desc: 'Açúcar de fruta, mais doce que glicose.' },
    { id: 'galactose', name: 'Galactose', symbol: 'C₆H₁₂O₆', category: 'ORGANIC_COMPOUND', desc: 'Açúcar do leite (lactose).' },
    { id: 'mannose', name: 'Manose', symbol: 'C₆H₁₂O₆', category: 'ORGANIC_COMPOUND', desc: 'Aldohexose.' },
    { id: 'ribose', name: 'Ribose', symbol: 'C₅H₁₀O₅', category: 'ORGANIC_COMPOUND', desc: 'Pentose do RNA.' },
    { id: 'deoxyribose', name: 'Desoxirribose', symbol: 'C₅H₁₀O₄', category: 'ORGANIC_COMPOUND', desc: 'Pentose do DNA.' },
    { id: 'sucrose', name: 'Sacarose', symbol: 'C₁₂H₂₂O₁₁', category: 'ORGANIC_COMPOUND', desc: 'Açúcar de mesa.' },
    { id: 'lactose', name: 'Lactose', symbol: 'C₁₂H₂₂O₁₁', category: 'ORGANIC_COMPOUND', desc: 'Açúcar do leite.' },
    { id: 'maltose', name: 'Maltose', symbol: 'C₁₂H₂₂O₁₁', category: 'ORGANIC_COMPOUND', desc: 'Açúcar do malte.' },
    { id: 'trehalose', name: 'Trealose', symbol: 'C₁₂H₂₂O₁₁', category: 'ORGANIC_COMPOUND', desc: 'Dissacarídeo protetor.' },
    { id: 'glucose_unit', name: 'Unidade de Glicose', symbol: 'C₆H₁₀O₅', category: 'ORGANIC_COMPOUND', desc: 'Monômero de polissacarídeos.' },
    
    // GRUPO 18: HETEROCICLOS AROMÁTICOS
    { id: 'anisole', name: 'Anisol', symbol: 'C₆H₅OCH₃', category: 'ORGANIC_COMPOUND', desc: 'Metoxi-benzeno, odor de anis.' },
    { id: 'pyridine', name: 'Piridina', symbol: 'C₅H₅N', category: 'ORGANIC_COMPOUND', desc: 'Heterociclo aromático, base nitrogenada.' },
    { id: 'quinoline', name: 'Quinolina', symbol: 'C₉H₇N', category: 'ORGANIC_COMPOUND', desc: 'Heterociclo bicíclico.' },
    { id: 'indole', name: 'Indol', symbol: 'C₈H₇N', category: 'ORGANIC_COMPOUND', desc: 'Heterociclo, feromônio.' },
    { id: 'imidazole', name: 'Imidazol', symbol: 'C₃H₄N₂', category: 'ORGANIC_COMPOUND', desc: 'Heterociclo, base nitrogenada.' },
    { id: 'purine', name: 'Purina', symbol: 'C₅H₄N₄', category: 'ORGANIC_COMPOUND', desc: 'Base nitrogenada, DNA/RNA.' },
    { id: 'pyrimidine', name: 'Pirimidina', symbol: 'C₄H₄N₂', category: 'ORGANIC_COMPOUND', desc: 'Base nitrogenada, DNA/RNA.' },
    { id: 'thiophene', name: 'Tiofeno', symbol: 'C₄H₄S', category: 'ORGANIC_COMPOUND', desc: 'Heterociclo com enxofre.' },
    { id: 'furan', name: 'Furano', symbol: 'C₄H₄O', category: 'ORGANIC_COMPOUND', desc: 'Heterociclo com oxigênio.' },
    { id: 'anthracene', name: 'Antraceno', symbol: 'C₁₄H₁₀', category: 'ORGANIC_COMPOUND', desc: 'PAH tricíclico, fluorescente.' },
    
    // GRUPO 19: VITAMINAS
    { id: 'thiamine', name: 'Tiamina', symbol: 'C₁₂H₁₇ClN₄OS', category: 'PHARMACEUTICAL', desc: 'Vitamina B1, coenzima metabólica.' },
    { id: 'riboflavin', name: 'Riboflavina', symbol: 'C₁₇H₂₀N₄O₆', category: 'PHARMACEUTICAL', desc: 'Vitamina B2, saúde ocular.' },
    { id: 'niacin', name: 'Niacina', symbol: 'C₆H₅NO₂', category: 'PHARMACEUTICAL', desc: 'Vitamina B3, metabolismo energético.' },
    { id: 'pantothenic_acid', name: 'Ácido Pantotênico', symbol: 'C₉H₁₇NO₅', category: 'PHARMACEUTICAL', desc: 'Vitamina B5, síntese de acetil-CoA.' },
    { id: 'pyridoxine', name: 'Piridoxina', symbol: 'C₈H₁₁NO₃', category: 'PHARMACEUTICAL', desc: 'Vitamina B6, metabolismo de aminoácidos.' },
    { id: 'biotin', name: 'Biotina', symbol: 'C₁₀H₁₆N₂O₃S', category: 'PHARMACEUTICAL', desc: 'Vitamina B7, cabelo e unhas.' },
    { id: 'folic_acid_pure', name: 'Ácido Fólico Puro', symbol: 'C₁₉H₁₉N₇O₆', category: 'PHARMACEUTICAL', desc: 'Vitamina B9, essencial gravidez.' },
    { id: 'cobalamin', name: 'Cobalamina', symbol: 'C₆₃H₈₈CoN₁₄O₁₄P', category: 'PHARMACEUTICAL', desc: 'Vitamina B12, sistema nervoso.' },
    { id: 'ascorbic_acid', name: 'Ácido Ascórbico', symbol: 'C₆H₈O₆', category: 'PHARMACEUTICAL', desc: 'Vitamina C, antioxidante.' },
    { id: 'tocopherol', name: 'Tocoferol', symbol: 'C₂₉H₅₀O₂', category: 'PHARMACEUTICAL', desc: 'Vitamina E, antioxidante potente.' },
    
    // GRUPO 20: COMPOSTOS FINAIS PARA PÓLVORA
    { id: 'potassium_nitrite', name: 'Nitrito de Potássio', symbol: 'KNO₂', category: 'INORGANIC_COMPOUND', desc: 'Precursor do nitrato de potássio.' },
    { id: 'nitrogen_dioxide', name: 'Dióxido de Nitrogênio', symbol: 'NO₂', category: 'INORGANIC_COMPOUND', desc: 'Gás marrom-avermelhado, oxidante.' },
    { id: 'sulfur_dioxide', name: 'Dióxido de Enxofre', symbol: 'SO₂', category: 'INORGANIC_COMPOUND', desc: 'Gás pungente, conservante.' },
    { id: 'carbon_black', name: 'Negro de Carbono', symbol: 'C', category: 'INORGANIC_COMPOUND', desc: 'Forma amorfa impura de carbono, pigmento.' },
    { id: 'gunpowder', name: 'Pólvora Negra', symbol: 'C+S+KNO₃', category: 'INORGANIC_COMPOUND', desc: 'Explosivo: carv\u00e3o, enxofre e nitrato de pot\u00e1ssio.' }
];
