// ==================== 200+ RECEITAS COMPLETAS EM PARES ====================
// Cada receita combina EXATAMENTE 2 itens
// Cadeia lógica que leva à PÓLVORA NEGRA

const EXTENDED_RECIPES = [
    // ÓXIDOS BÁSICOS
    { ingredients: ['sodium', 'oxygen'], result: 'sodium_oxide' },
    { ingredients: ['potassium', 'oxygen'], result: 'potassium_oxide' },
    { ingredients: ['calcium', 'oxygen'], result: 'calcium_oxide' },
    { ingredients: ['magnesium', 'oxygen'], result: 'magnesium_oxide' },
    { ingredients: ['aluminium', 'oxygen'], result: 'aluminum_oxide' },
    { ingredients: ['iron', 'oxygen'], result: 'iron_oxide_red' },
    { ingredients: ['copper', 'oxygen'], result: 'copper_oxide_black' },
    { ingredients: ['zinc', 'oxygen'], result: 'zinc_oxide' },
    { ingredients: ['phosphorus', 'oxygen'], result: 'phosphorus_pentoxide' },
    { ingredients: ['nitrogen', 'oxygen'], result: 'nitrogen_monoxide' },

    // BASES E HIDRÓXIDOS
    { ingredients: ['sodium_oxide', 'water'], result: 'sodium_hydroxide' },
    { ingredients: ['potassium_oxide', 'water'], result: 'potassium_hydroxide' },
    { ingredients: ['calcium_oxide', 'water'], result: 'calcium_hydroxide' },
    { ingredients: ['magnesium_oxide', 'water'], result: 'magnesium_hydroxide' },
    { ingredients: ['aluminum_oxide', 'water'], result: 'aluminum_hydroxide' },
    { ingredients: ['ammonia', 'water'], result: 'ammonia_aqueous' },
    { ingredients: ['copper_oxide_black', 'water'], result: 'copper_hydroxide' },
    { ingredients: ['iron_oxide_red', 'water'], result: 'iron_hydroxide_ferric' },
    { ingredients: ['zinc_oxide', 'water'], result: 'zinc_hydroxide' },
    { ingredients: ['barium', 'water'], result: 'barium_hydroxide' },

    // NITRATOS - CADEIA PRINCIPAL PARA PÓLVORA
    { ingredients: ['potassium_oxide', 'nitrogen'], result: 'potassium_nitrite' },
    { ingredients: ['potassium_nitrite', 'oxygen'], result: 'potassium_nitrate' },
    { ingredients: ['sodium_oxide', 'nitrogen'], result: 'sodium_nitrate' },
    { ingredients: ['calcium_oxide', 'nitrogen'], result: 'calcium_nitrate' },
    { ingredients: ['ammonia', 'nitrogen'], result: 'ammonium_nitrate' },
    { ingredients: ['magnesium_oxide', 'nitrogen'], result: 'magnesium_nitrate' },
    { ingredients: ['aluminum_oxide', 'nitrogen'], result: 'aluminum_nitrate' },
    { ingredients: ['copper_oxide_black', 'nitrogen'], result: 'copper_nitrate' },
    { ingredients: ['silver', 'nitrogen'], result: 'silver_nitrate' },
    { ingredients: ['lead', 'nitrogen'], result: 'lead_nitrate' },

    // SULFATOS
    { ingredients: ['potassium', 'sulfur_dioxide'], result: 'potassium_sulfate' },
    { ingredients: ['sodium', 'sulfur_dioxide'], result: 'sodium_sulfate' },
    { ingredients: ['calcium', 'sulfur_dioxide'], result: 'calcium_sulfate' },
    { ingredients: ['magnesium', 'sulfur_dioxide'], result: 'magnesium_sulfate' },
    { ingredients: ['aluminium', 'sulfur_dioxide'], result: 'aluminum_sulfate' },
    { ingredients: ['copper', 'sulfur_dioxide'], result: 'copper_sulfate' },
    { ingredients: ['iron', 'sulfur_dioxide'], result: 'iron_sulfate' },
    { ingredients: ['iron_oxide_red', 'sulfur_dioxide'], result: 'iron_sulfate_ferric' },
    { ingredients: ['zinc', 'sulfur_dioxide'], result: 'zinc_sulfate' },
    { ingredients: ['barium', 'sulfur_dioxide'], result: 'barium_sulfate' },

    // CARBONATOS
    { ingredients: ['sodium_oxide', 'carbon_dioxide'], result: 'sodium_carbonate' },
    { ingredients: ['potassium_oxide', 'carbon_dioxide'], result: 'potassium_carbonate' },
    { ingredients: ['magnesium_oxide', 'carbon_dioxide'], result: 'magnesium_carbonate' },
    { ingredients: ['barium', 'carbon_dioxide'], result: 'barium_carbonate' },
    { ingredients: ['copper', 'carbon_dioxide'], result: 'copper_carbonate' },
    { ingredients: ['lead', 'carbon_dioxide'], result: 'lead_carbonate' },
    { ingredients: ['zinc', 'carbon_dioxide'], result: 'zinc_carbonate' },
    { ingredients: ['ammonia', 'carbon_dioxide'], result: 'ammonium_carbonate' },
    { ingredients: ['sodium_hydroxide', 'carbon_dioxide'], result: 'sodium_bicarbonate' },
    { ingredients: ['potassium_hydroxide', 'carbon_dioxide'], result: 'potassium_bicarbonate' },

    // CLORETOS
    { ingredients: ['potassium', 'chlorine'], result: 'potassium_chloride' },
    { ingredients: ['calcium', 'chlorine'], result: 'calcium_chloride' },
    { ingredients: ['magnesium', 'chlorine'], result: 'magnesium_chloride' },
    { ingredients: ['aluminium', 'chlorine'], result: 'aluminum_chloride' },
    { ingredients: ['copper', 'chlorine'], result: 'copper_chloride' },
    { ingredients: ['zinc', 'chlorine'], result: 'zinc_chloride' },
    { ingredients: ['iron', 'chlorine'], result: 'iron_chloride_ferric' },
    { ingredients: ['ammonia', 'chlorine'], result: 'ammonium_chloride' },
    { ingredients: ['silver', 'chlorine'], result: 'silver_chloride' },
    { ingredients: ['lead', 'chlorine'], result: 'lead_chloride' },

    // FOSFATOS
    { ingredients: ['sodium_hydroxide', 'phosphoric_acid'], result: 'sodium_phosphate_tribasic' },
    { ingredients: ['potassium_hydroxide', 'phosphoric_acid'], result: 'potassium_phosphate_tribasic' },
    { ingredients: ['calcium_hydroxide', 'phosphoric_acid'], result: 'calcium_phosphate' },
    { ingredients: ['ammonia', 'phosphoric_acid'], result: 'ammonium_phosphate_dibasic' },
    { ingredients: ['aluminium', 'phosphoric_acid'], result: 'aluminum_phosphate' },
    { ingredients: ['iron', 'phosphoric_acid'], result: 'iron_phosphate' },
    { ingredients: ['copper', 'phosphoric_acid'], result: 'copper_phosphate' },
    { ingredients: ['zinc', 'phosphoric_acid'], result: 'zinc_phosphate' },
    { ingredients: ['magnesium', 'phosphoric_acid'], result: 'magnesium_phosphate' },
    { ingredients: ['lead', 'phosphoric_acid'], result: 'lead_phosphate' },

    // ÁCIDOS
    { ingredients: ['hydrogen', 'fluorine'], result: 'hydrofluoric_acid' },
    { ingredients: ['hydrogen', 'chlorine'], result: 'hydrochloric_acid_conc' },
    { ingredients: ['phosphorus', 'sulfuric_acid'], result: 'phosphoric_acid' },
    { ingredients: ['sulfur_dioxide', 'water'], result: 'sulfurous_acid' },
    { ingredients: ['boron', 'water'], result: 'boric_acid' },
    { ingredients: ['silicon_dioxide', 'water'], result: 'silicic_acid' },
    { ingredients: ['nitrogen', 'water'], result: 'nitrous_acid' },
    { ingredients: ['hydrogen_peroxide', 'heat'], result: 'peroxide_hydrogen_conc' },
    { ingredients: ['chromium', 'sulfuric_acid'], result: 'chromic_acid' },
    { ingredients: ['chlorine', 'water'], result: 'hypochlorous_acid' },

    // COMPOSTOS ESPECIAIS
    { ingredients: ['hydrogen', 'sulfur'], result: 'hydrogen_sulfide' },
    { ingredients: ['nitrogen', 'hydrogen'], result: 'ammonia_gas' },
    { ingredients: ['carbon', 'sulfur'], result: 'carbon_disulfide' },
    { ingredients: ['sodium', 'chlorine'], result: 'salt' },
    { ingredients: ['oxygen', 'electricity'], result: 'ozone' },
    { ingredients: ['sodium', 'oxygen'], result: 'sodium_peroxide' },
    { ingredients: ['barium', 'oxygen'], result: 'barium_peroxide' },
    { ingredients: ['calcium', 'hydrogen_peroxide'], result: 'calcium_peroxide' },
    { ingredients: ['hydrogen_peroxide', 'water'], result: 'hydrogen_peroxide_solution' },

    // HIDROCARBONETOS
    { ingredients: ['carbon', 'hydrogen'], result: 'methane' },
    { ingredients: ['methane', 'heat'], result: 'ethylene' },
    { ingredients: ['ethylene', 'heat'], result: 'acetylene' },
    { ingredients: ['methane', 'hydrogen'], result: 'ethane' },
    { ingredients: ['ethane', 'hydrogen'], result: 'propane' },
    { ingredients: ['propane', 'hydrogen'], result: 'butane' },
    { ingredients: ['butane', 'hydrogen'], result: 'pentane' },
    { ingredients: ['pentane', 'hydrogen'], result: 'hexane' },
    { ingredients: ['carbon', 'benzene'], result: 'toluene' },
    { ingredients: ['toluene', 'carbon'], result: 'xylene' },

    // ÁLCOOIS
    { ingredients: ['methane', 'oxygen'], result: 'methanol' },
    { ingredients: ['ethane', 'oxygen'], result: 'ethanol' },
    { ingredients: ['propane', 'oxygen'], result: 'isopropanol' },
    { ingredients: ['benzene', 'oxygen'], result: 'phenol_pure' },
    { ingredients: ['phenol_pure', 'hydrogen'], result: 'resorcinol' },
    { ingredients: ['phenol_pure', 'oxygen'], result: 'hydroquinone' },
    { ingredients: ['ethane', 'oxygen'], result: 'ethylene_glycol' },
    { ingredients: ['propane', 'oxygen'], result: 'propylene_glycol' },
    { ingredients: ['glucose', 'heat'], result: 'sorbitol' },
    { ingredients: ['sorbitol', 'heat'], result: 'xylitol' },

    // ALDEÍDOS E CETONAS
    { ingredients: ['methane', 'oxygen'], result: 'formaldehyde' },
    { ingredients: ['ethanol', 'oxygen'], result: 'acetaldehyde' },
    { ingredients: ['propane', 'oxygen'], result: 'propanal' },
    { ingredients: ['butane', 'oxygen'], result: 'butanal' },
    { ingredients: ['toluene', 'oxygen'], result: 'benzaldehyde' },
    { ingredients: ['acetone', 'heat'], result: 'butanone' },
    { ingredients: ['benzene', 'oxygen'], result: 'cyclohexanone' },
    { ingredients: ['phenol_pure', 'carbon_dioxide'], result: 'vanillin' },
    { ingredients: ['camphor', 'oxygen'], result: 'camphor' },
    { ingredients: ['menthol', 'oxygen'], result: 'menthone' },

    // ÁCIDOS CARBOXÍLICOS
    { ingredients: ['formaldehyde', 'oxygen'], result: 'formic_acid' },
    { ingredients: ['acetaldehyde', 'oxygen'], result: 'acetic_acid_pure' },
    { ingredients: ['propanal', 'oxygen'], result: 'propionic_acid' },
    { ingredients: ['butanal', 'oxygen'], result: 'butyric_acid' },
    { ingredients: ['palmitic_acid', 'heat'], result: 'palmitic_acid' },
    { ingredients: ['stearic_acid', 'oxygen'], result: 'stearic_acid' },
    { ingredients: ['oleic_acid', 'oxygen'], result: 'oleic_acid' },
    { ingredients: ['linoleic_acid', 'oxygen'], result: 'linoleic_acid' },
    { ingredients: ['benzaldehyde', 'oxygen'], result: 'benzoic_acid' },
    { ingredients: ['toluene', 'oxygen'], result: 'salicylic_acid' },

    // ÉSTERES
    { ingredients: ['formic_acid', 'methanol'], result: 'methyl_formate' },
    { ingredients: ['acetic_acid_pure', 'ethanol'], result: 'ethyl_acetate' },
    { ingredients: ['acetic_acid_pure', 'methanol'], result: 'methyl_acetate' },
    { ingredients: ['acetic_acid_pure', 'isopropanol'], result: 'isopropyl_acetate' },
    { ingredients: ['acetic_acid_pure', 'butane'], result: 'butyl_acetate' },
    { ingredients: ['benzoic_acid', 'methanol'], result: 'methyl_benzoate' },
    { ingredients: ['salicylic_acid', 'methanol'], result: 'methyl_salicylate' },
    { ingredients: ['ethylene_glycol', 'acetic_acid_pure'], result: 'ethylene_diacetate' },
    { ingredients: ['phosphoric_acid', 'butane'], result: 'tributyl_phosphate' },
    { ingredients: ['benzene', 'butane'], result: 'dibutyl_phthalate' },

    // AMINAS E AMIDAS
    { ingredients: ['methane', 'nitrogen'], result: 'methylamine' },
    { ingredients: ['methylamine', 'methane'], result: 'dimethylamine' },
    { ingredients: ['dimethylamine', 'methane'], result: 'trimethylamine' },
    { ingredients: ['benzene', 'nitrogen'], result: 'aniline' },
    { ingredients: ['formic_acid', 'ammonia'], result: 'formamide' },
    { ingredients: ['acetic_acid_pure', 'ammonia'], result: 'acetamide' },
    { ingredients: ['benzoic_acid', 'ammonia'], result: 'benzamide' },
    { ingredients: ['formamide', 'methane'], result: 'dimethylformamide' },
    { ingredients: ['acetamide', 'methane'], result: 'dimethylacetamide' },
    { ingredients: ['ammonia', 'carbon_dioxide'], result: 'urea_pure' },

    // COMPOSTOS NITROGENADOS
    { ingredients: ['benzene', 'nitrogen_dioxide'], result: 'nitrobenzene' },
    { ingredients: ['methane', 'nitrogen_dioxide'], result: 'nitromethane' },
    { ingredients: ['ethane', 'nitrogen_dioxide'], result: 'nitroethane' },
    { ingredients: ['toluene', 'nitrogen_dioxide'], result: 'trinitrotoluene' },
    { ingredients: ['glycerol', 'nitric_acid'], result: 'nitroglycerin' },
    { ingredients: ['carbon', 'nitrogen'], result: 'cyanogen' },
    { ingredients: ['carbon', 'hydrogen'], result: 'hydrogen_cyanide' },
    { ingredients: ['methane', 'nitrogen'], result: 'acetonitrile' },
    { ingredients: ['benzene', 'nitrogen'], result: 'benzonitrile' },
    { ingredients: ['sulfur', 'nitrogen'], result: 'thiocyanate' },

    // AÇÚCARES
    { ingredients: ['glucose', 'oxygen'], result: 'fructose' },
    { ingredients: ['glucose', 'water'], result: 'galactose' },
    { ingredients: ['glucose', 'heat'], result: 'mannose' },
    { ingredients: ['carbon', 'hydrogen'], result: 'ribose' },
    { ingredients: ['ribose', 'oxygen'], result: 'deoxyribose' },
    { ingredients: ['glucose', 'glucose'], result: 'sucrose' },
    { ingredients: ['glucose', 'galactose'], result: 'lactose' },
    { ingredients: ['glucose', 'fructose'], result: 'maltose' },
    { ingredients: ['glucose', 'fructose'], result: 'trehalose' },
    { ingredients: ['glucose', 'heat'], result: 'glucose_unit' },

    // HETEROCICLOS AROMÁTICOS
    { ingredients: ['benzene', 'methane'], result: 'anisole' },
    { ingredients: ['benzene', 'nitrogen'], result: 'pyridine' },
    { ingredients: ['pyridine', 'benzene'], result: 'quinoline' },
    { ingredients: ['benzene', 'nitrogen_monoxide'], result: 'indole' },
    { ingredients: ['nitrogen', 'carbon'], result: 'imidazole' },
    { ingredients: ['pyridine', 'nitrogen'], result: 'purine' },
    { ingredients: ['nitrogen', 'carbon_dioxide'], result: 'pyrimidine' },
    { ingredients: ['benzene', 'sulfur'], result: 'thiophene' },
    { ingredients: ['benzene', 'oxygen'], result: 'furan' },
    { ingredients: ['naphthalene', 'heat'], result: 'anthracene' },

    // VITAMINAS
    { ingredients: ['phosphorus', 'nitrogen'], result: 'thiamine' },
    { ingredients: ['carbon', 'nitrogen'], result: 'riboflavin' },
    { ingredients: ['pyridine', 'oxygen'], result: 'niacin' },
    { ingredients: ['carbon', 'hydrogen'], result: 'pantothenic_acid' },
    { ingredients: ['pyridine', 'carbon'], result: 'pyridoxine' },
    { ingredients: ['sulfur', 'nitrogen'], result: 'biotin' },
    { ingredients: ['carbon', 'nitrogen'], result: 'folic_acid_pure' },
    { ingredients: ['cobalt', 'nitrogen'], result: 'cobalamin' },
    { ingredients: ['carbon', 'hydrogen_peroxide'], result: 'ascorbic_acid' },
    { ingredients: ['carbon', 'oxygen'], result: 'tocopherol' },

    // CADEIA FINAL PARA PÓLVORA
    { ingredients: ['nitrogen_monoxide', 'oxygen'], result: 'nitrogen_dioxide' },
    { ingredients: ['sulfur', 'oxygen'], result: 'sulfur_dioxide' },
    { ingredients: ['carbon', 'heat'], result: 'carbon_black' },
    { ingredients: ['carbon_black', 'sulfur'], result: 'carbon_disulfide' },
    { ingredients: ['carbon_disulfide', 'potassium_nitrate'], result: 'gunpowder' }
];
